import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { initializeApp } from 'firebase/app';
import { getMessaging, getToken, onMessage } from 'firebase/messaging';
import { useEffect } from 'react';

const firebaseConfig = {
    apiKey: 'AIzaSyByidRXJUjgH5kt1EcAJkEr-GZ3PN2oc_E',
    authDomain: 'push-test-5dcd2.firebaseapp.com',
    projectId: 'push-test-5dcd2',
    storageBucket: 'push-test-5dcd2.appspot.com',
    messagingSenderId: '743305519810',
    appId: '1:743305519810:web:bbf02c3b4a68e6857d915b',
    measurementId: 'G-MM4CPDB5PV',
};

function requestPermission() {
    console.log('Requesting permission...');
    Notification.requestPermission().then((permission) => {
        if (permission === 'granted') {
            console.log('Notification permission granted.');
        }
    });
}

export default function Home() {

    useEffect(() => {
        // Initialize Firebase
        const app = initializeApp(firebaseConfig);
        const messaging = getMessaging(app);

        getToken(messaging, {
            vapidKey:
                'BEIWmMf5d6HuF_SLqXu7abILgxVQXk-j0e4LPRqhyfrqchHyfBglLJN9C-aXhzW4c0OjQPW58__xZL9AkKi3-Pk',
        }).then((token) => {
            if (token) {
                // Send the token to your server and update the UI if necessary
                // ...
            } else {
                // Show permission request UI
                console.log(
                    'No registration token available. Request permission to generate one.'
                );
                // ...
            }
        });

        requestPermission();

        onMessage(messaging, (payload) => {
          console.log('onMessage: ', payload);
        });
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href='https://nextjs.org'>Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.js</code>
                </p>

                <div className={styles.grid}>
                    <a href='https://nextjs.org/docs' className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>
                            Find in-depth information about Next.js features and
                            API.
                        </p>
                    </a>

                    <a href='https://nextjs.org/learn' className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>
                            Learn about Next.js in an interactive course with
                            quizzes!
                        </p>
                    </a>

                    <a
                        href='https://github.com/vercel/next.js/tree/canary/examples'
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>
                            Discover and deploy boilerplate example Next.js
                            projects.
                        </p>
                    </a>

                    <a
                        href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                        target='_blank'
                        rel='noopener noreferrer'
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL
                            with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                    target='_blank'
                    rel='noopener noreferrer'
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image
                            src='/vercel.svg'
                            alt='Vercel Logo'
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
